### ISSUE TITLE
Cannot Use Both Email and Phone Providers Simultaneously

### ISSUE THREAD

**Issue by MuddasirAlgoace** [supabase/auth#1839] opened 2024-11-13 07:49 UTC
I am trying to register a user using both email and phone authentication in Flutter app with Supabase, but encountering the following error:

```
149 - assert((email != null && phone == null) || (email == null && phone != null),
150 - 'You must provide either an email or phone number');
```

This error arises because Supabase currently enforces a condition where only one of either email or phone is provided for user signup. However, I want to allow both email and phone parameters to be provided simultaneously, as it would make verification easier before future authentications.

Is there a way to modify or extend the logic in Supabase to support both email and phone authentication providers during signup? and their provider must be working on login seprately.

**Comment by J0** [comment] 2024-11-14 03:35
Closing as duplicate of #1840

**Closed by J0** 2024-11-14 03:35 UTC
Labels: bug
